### ISSUE TITLE
Not working with Zabbix 5.2

### ISSUE THREAD

**Issue by FloMeyer** [BernhardLinz/zabbix-ldap-sync-bash#1]
Create Combination ..................................................: XXX
curl -k -s -X POST -H "Content-Type:application/json" -d '{"jsonrpc": "2.0","method":"user.create","params":{"alias":"Username","name":"Max","surname":"Mustermann","user_medias":[{"mediatypeid": "1","sendto":["xxx.yyy@zzz.de"]}],"usrgrps":[{"usrgrpid":"14"}],"type":3},"id":42,"auth":"7358d61dc3b2737cb7cf1e3c9eb7beef"}'http://zabbix-server/api_jsonrpc.php
{"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid params.","data":"Invalid parameter \"/1\": unexpected parameter \"type\"."},"id":42}

Update Zabbix Group auth_ldap via API (Replace)curl -k -s -X POST -H "Content-Type:application/json"  -d '{"jsonrpc": "2.0","method":"usergroup.update","params":{"usrgrpid":"14","userids":["create-user","create-user","create-user","creat                                                                                                                                                e-user","create-user","create-user"]},"id":42,"auth":"7358d61dc3b2737cb7cf1e3c9eb7beef"}' http://zabbix-server/api_jsonrpc.php
{"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid params.","data":"Invalid parameter \"/1/userids/1\": a number is expected."},"id":42}

**Comment by BernhardLinz** [comment]
yes, they dropped the support of the type-parameter:
[https://www.zabbix.com/documentation/current/manual/api/changes_5.0_-_5.2](https://support.zabbix.com/browse/ZBXNEXT-6148) and [https://support.zabbix.com/browse/ZBXNEXT-6148](https://support.zabbix.com/browse/ZBXNEXT-6148) 

After a quick look in the new API-Reference it looks like i have to check the zabbix-version and use one solution for Zabbix 2 to 5 and a new solution for Zabbix > 5

I will take a look in the next days (and built a 5.2 test eviroment) and check how the roles are manged

**Comment by BernhardLinz** [comment]
New Version 1.2 released wich support the new roleid. Script now autodetect the Zabbix API version and select the "type" or the "roleid" method.
Because there are 3 predefinied user roles in Zabbix 5.2 wich correspond to the old user types there should be no problems with updates
