### ISSUE TITLE
Error in user.create on zabbix 6.2

### ISSUE THREAD

**Issue by awsmaythem** [BernhardLinz/zabbix-ldap-sync-bash#12]
Hi
https://www.zabbix.com/documentation/current/en/manual/api/reference/user/create
when i run the script at the step create user in zabbix it give me
"passwd\": cannot be empty."
how to solve it?

**Comment by BernhardLinz** [comment]
It will only work if you have changed the default login method of zabbix changed to ldap
take a look to the manual

**Comment by BernhardLinz** [comment]
not a script problem
